// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG-yt8n8yewcabmgsWQ92J3D69mNrh44s',
    appId: '1:614836085521:web:4d3a5564c5ee2f18f522b0',
    messagingSenderId: '614836085521',
    projectId: 'kasumi-bass',
    authDomain: 'kasumi-bass.firebaseapp.com',
    storageBucket: 'kasumi-bass.appspot.com',
    measurementId: 'G-TJE8ZEVVW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS10gaV4_B-6b_Y_rRNAyyNf79BoMp_tI',
    appId: '1:614836085521:android:f484ce0d93388f54f522b0',
    messagingSenderId: '614836085521',
    projectId: 'kasumi-bass',
    storageBucket: 'kasumi-bass.appspot.com',
  );
}
